common:
  target_module: audio
  task_type: audio_classification
  target_device: MSPM0G5187
dataset:
  dataset_name: google_speech_classification_1
  # input_data_path: /mnt/c/Users/a0507182/tensorlab/tinyml-modelzoo/google_speech_command/SpeechCommands/classes
  input_data_path: C:\Users\a0507182\tensorlab\tinyml-modelzoo\examples\google_speech_command\SpeechCommands
data_processing_feature_extraction:
  feature_extraction_name: GoogleSpeechCommands_MFCC_Default
training:
  model_name: DSCNN_NPU
  batch_size: 64
  training_epochs: 3
  num_gpus: 0
  quantization: 2
  learning_rate: 0.1
  weight_decay: 1e-5
testing: {}
compilation: {}