common:
  target_module: audio
  task_type: audio_classification
  target_device: MSPM0G5187

dataset:
  dataset_name: wake_word_detection
  input_data_path: https://software-dl.ti.com/C2000/esd/mcu_ai/datasets/wake_word_detection.zip
  
data_processing_feature_extraction:
  sampling_rate: 8000
  audio_duration_ms: 2000
  audio_feature: "FB"
  normalize_audio: False
  mono: True
  variables: 1
  # Filterbank parameters
  fb_conv_kernel: 32
  fb_output_channel: 64
  fb_bitwidth: 8
  input_bit_depth: 14

training:
  model_name: TCDS_ResNet_FB_NPU
  batch_size: 256
  training_epochs: 30
  num_gpus: 0
  quantization: 2
  learning_rate: 0.001
  weight_decay: 1e-5

testing: {}

compilation: {}